"""Offline OCR with the Tesseract command-line tool (no network).

Quality is usually below that of vision models, especially for handwriting, low-quality scans
and complex layouts, but it needs no account and sends nothing anywhere.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile

from ..i18n import N_
from .base import ExtractCapabilities, ProviderError, ProviderUnavailable

LANG_RE_ALLOWED = set("abcdefghijklmnopqrstuvwxyz_+")


class TesseractExtractor:
    name = "tesseract"
    target = N_("local")
    adapter_version = "tesseract-v1"
    capabilities = ExtractCapabilities(images=True, pdf=False)

    def __init__(self, timeout: int = 180, binary: str | None = None):
        self.binary = binary or shutil.which("tesseract")
        if not self.binary:
            raise ProviderUnavailable(
                N_("Tesseract is not installed (package “tesseract-ocr” + language data “deu”).")
            )
        self.timeout = timeout
        self.model = self._version()

    def _version(self) -> str:
        try:
            out = subprocess.run(
                [self.binary, "--version"], capture_output=True, text=True, timeout=10, check=False
            )
            first = (out.stdout or out.stderr).splitlines()[0]
            return first.strip()
        except (OSError, subprocess.TimeoutExpired, IndexError):
            return "tesseract"

    def available_languages(self) -> set[str]:
        out = subprocess.run(
            [self.binary, "--list-langs"], capture_output=True, text=True, timeout=10, check=False
        )
        return {ln.strip() for ln in out.stdout.splitlines()[1:] if ln.strip()}

    def _run(self, image_png: bytes, page_number: int, languages: str, *extra: str) -> str:
        if not set(languages) <= LANG_RE_ALLOWED:
            raise ProviderUnavailable(N_("Invalid OCR language setting"))
        # file names are generated by us; no user-controlled data reaches the command line
        with tempfile.TemporaryDirectory(prefix="heftig-ocr-") as tmp:
            src = os.path.join(tmp, "page.png")
            with open(src, "wb") as f:
                f.write(image_png)
            env = dict(os.environ, OMP_THREAD_LIMIT="1")
            try:
                proc = subprocess.run(
                    [self.binary, src, "stdout", "-l", languages, "--psm", "3", *extra],
                    capture_output=True,
                    timeout=self.timeout,
                    env=env,
                    check=False,
                )
            except subprocess.TimeoutExpired as e:
                raise ProviderError(
                    N_("Tesseract time limit exceeded on page %(page)s") % {"page": page_number},
                    transient=False,
                ) from e
            if proc.returncode != 0:
                msg = proc.stderr.decode("utf-8", "replace").strip().splitlines()[-1:] or ["?"]
                raise ProviderError(
                    N_("Tesseract error on page %(page)s: %(error)s")
                    % {"page": page_number, "error": msg[0][:200]}
                )
            return proc.stdout.decode("utf-8", "replace")

    def extract_page(
        self, image: bytes, page_number: int, languages: str, media_type: str = "image/png"
    ) -> str:
        return self._run(image, page_number, languages)

    def word_boxes(
        self, image_png: bytes, page_number: int, languages: str
    ) -> list[tuple[str, int, int, int, int]]:
        """Recognised words with pixel boxes (left, top, right, bottom)."""
        out = []
        for line in self._run(image_png, page_number, languages, "tsv").splitlines()[1:]:
            cols = line.split("\t")
            if len(cols) < 12 or cols[0] != "5" or not cols[11].strip():
                continue
            try:
                x, y, w, h = (int(c) for c in cols[6:10])
            except ValueError:
                continue
            out.append((cols[11].strip(), x, y, x + w, y + h))
        return out
